version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: sf2-neo4j
    ports:
      - "7474:7474"  
      - "7687:7687"  
    environment:
      NEO4J_AUTH: none
    volumes:
      - ./init:/var/lib/neo4j/import
      - neo4j-data:/data

volumes:
  neo4j-data:

