name: Test

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  test-backend:
    # backendディレクトリに変更がある場合のみ実行
    if: |
      contains(github.event.push.commits.*.modified, 'backend/') ||
      contains(github.event.push.commits.*.added, 'backend/') ||
      contains(github.event.push.commits.*.removed, 'backend/') ||
      contains(github.event.pull_request.files.*.filename, 'backend/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Run backend tests
        working-directory: backend
        run: npm test
        
  test-frontend:
    runs-on: ubuntu-latest
    # frontendディレクトリに変更がある場合のみ実行
    if: |
      contains(github.event.push.commits.*.modified, 'frontend/') ||
      contains(github.event.push.commits.*.added, 'frontend/') ||
      contains(github.event.push.commits.*.removed, 'frontend/') ||
      contains(github.event.pull_request.files.*.filename, 'frontend/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test:run
